/** PRD Section 2.9 About sections and Section 2.10 disclosure language. */

export const ABOUT_PLATFORM = {
  title: "About LetNumbersTalk",
  paragraphs: [
    "LetNumbersTalk tells a founder or operating leader where their business is actually strong, where it is quietly fragile, and which of those findings deserves attention first. It reads 54 figures already sitting in the accounting system, the CRM, the payroll register and the operations log, and returns a diagnosis: a score for each dimension of the business, a plain-language reading of every figure entered, and — wherever a reading falls outside its healthy range — the place in the value chain where that finding usually originates, the factors that commonly contribute to it, and concrete illustrations of how it presents in practice.",
    "The benchmark sets behind those readings are built on AI-augmented research synthesis: sector-specific ranges assembled and cross-checked across 5 business profiles, so a services firm is never measured against SaaS expectations and a pre-profitability startup is never held to manufacturing norms. That calibration is what makes the diagnosis usable rather than merely numerical.",
    "The user walks away able to see the business as an assessor would see it — with the weak seams named, the strong ones confirmed, and the sequence of attention made obvious.",
    "The architecture underneath: 7 independently weighted pillars — Financial Health at 22%, Risk Management at 20, Market Position at 18, Operational Efficiency at 15, Strategic Positioning at 13, Organizational Capability at 7, and Technology and Systems at 5. Each pillar carries its own scoring engine, converting its constituent metrics into a 0-to-100 score against sector-calibrated bands. Where metrics are left blank, the engine re-weights across only what was entered; nothing is scored as zero for being unknown. Assessing all 7 pillars produces an Integrated Business Health Score as a weighted composite. Every figure entered stays in the browser: no account, no transmission, no storage.",
  ],
};

export const ABOUT_ARCHITECT = {
  title: "Conceptualized by Mr Sajal Roy",
  paragraphs: [
    "LetNumbersTalk was conceptualized by Mr Sajal Roy, an Enterprise Systems Architect who builds and runs systems that help founders and boardroom leaders with decision intelligence. His practice spans management and strategy consulting, AI-augmented business solutions, large-scale program governance, operations management, business transformation and executive mentoring, drawing on a decade of continued experience across complex enterprise ecosystems and multi-stakeholder delivery at scale.",
    "The instrument reflects that practice directly. The 7 pillars mirror the dimensions along which enterprise performance is reviewed at board level. The 54 metrics are the figures a consulting engagement would request in its first week. The scoring logic encodes what an experienced assessor concludes when a gross margin, a runway figure and a concentration ratio are read together rather than separately, and the guidance layer carries the diagnostic reasoning that would otherwise arrive verbally in a review room.",
    "He contributes to the founder ecosystem through the LinkedIn newsletter Strategy Consulting Weekly and the podcast The Clarity Dispatch on Spotify, and works pro bono with founders applying the frameworks of management and strategy consulting to early and scaling businesses.",
    "LetNumbersTalk is the convergence point of that work: management and strategy consulting discipline fused with product management thinking to produce a scalable decision-intelligence instrument.",
  ],
  credentials: [
    "Microsoft Certified AI Transformation Leader",
    "Enterprise Operations Excellence and Program Governance",
    "Management and Strategy Consulting Practitioner",

    "SAFe 6 Agilist",
    "Certified Scrum Master",
    "ICP-ACC Agile Coach",
    "Kanban KMP1",
  ],
  contact: "roysajal5@gmail.com",
  contactLabel: "Mail",
  name: "Mr Sajal Roy",
  role: "Enterprise Systems Architect",
  linkedin: "",
  workspaceUrl: "https://linktr.ee/sajalroy",
  workspaceLabel: "Spotify Podcast | LinkedIn Newsletter | Socials",
};

export const METHODOLOGY_NOTE =
  "This diagnostic capability is constituted through AI-augmented research synthesis and the deliberate fusion of Product Management and Management Consulting frameworks, held to the standard of evidence a board applies to any figure placed before it.";

export const DISCLOSURE = {
  title: "Application Disclaimer",
  body: "This instrument issues a structured, evidence-led reading of enterprise condition. The diagnostic readings, scoring, and Areas to Look Into content generated by this application are presented as a structured self-assessment resource, built on AI-augmented research synthesis, and contributed for informational purposes. They are intended to support informed decision-making, not to substitute for it. Every business context carries variables that no automated assessment can fully account for. Accordingly, the outputs of this application are to be read alongside qualified professional counsel, and reviewed with advisors of standing, before they are translated into structural, operational, financial, or investment commitments.",
};
